#!/bin/bash

echo Building project..
start=$SECONDS

echo Copying static files..
cp -r ./src/static ./bin/static
echo Done.

echo Transpiling TypeScript..
tsc
echo Done.

duration=$(( SECONDS - start ))
echo Finished building in ${duration}s.